"""Static, realistic roster + stat-baseline data used by the mock provider.

Each player carries season-average baselines per stat type. The mock
generator turns these into prop lines, projections, game logs and hit
rates. Replacing this module (or the provider) with live data does not
touch the API surface.
"""
from __future__ import annotations

# sport key -> metadata
SPORTS = [
    {
        "key": "baseball_mlb",
        "name": "MLB",
        "full_name": "Major League Baseball",
        "icon": "⚾",
        "season": "in-season",
        "active": True,
        "stat_types": ["Hits", "Total Bases", "Home Runs", "RBIs", "Runs", "Stolen Bases"],
    },
    {
        "key": "basketball_wnba",
        "name": "WNBA",
        "full_name": "Women's National Basketball Association",
        "icon": "🏀",
        "season": "in-season",
        "active": True,
        "stat_types": ["Points", "Rebounds", "Assists", "3-Pointers Made", "Pts+Reb+Ast"],
    },
    {
        "key": "americanfootball_nfl",
        "name": "NFL",
        "full_name": "National Football League",
        "icon": "🏈",
        "season": "offseason",
        "active": False,
        "stat_types": ["Passing Yards", "Rushing Yards", "Receiving Yards", "Receptions", "Passing TDs"],
    },
    {
        "key": "americanfootball_ncaaf",
        "name": "NCAAF",
        "full_name": "NCAA Football",
        "icon": "🎓",
        "season": "offseason",
        "active": False,
        "stat_types": ["Passing Yards", "Rushing Yards", "Receiving Yards", "Passing TDs"],
    },
    {
        "key": "basketball_ncaab",
        "name": "NCAAB",
        "full_name": "NCAA Basketball",
        "icon": "🏀",
        "season": "offseason",
        "active": False,
        "stat_types": ["Points", "Rebounds", "Assists", "3-Pointers Made"],
    },
]

# sport key -> list of players with season-average baselines per stat type.
# The first stat in each "stats" dict is treated as the player's primary stat.
ROSTERS = {
    "baseball_mlb": [
        {"name": "Aaron Judge", "team": "New York Yankees", "team_abbr": "NYY", "position": "RF",
         "stats": {"Hits": 1.3, "Total Bases": 2.7, "Home Runs": 0.45, "RBIs": 1.1, "Runs": 1.1, "Stolen Bases": 0.1}},
        {"name": "Shohei Ohtani", "team": "Los Angeles Dodgers", "team_abbr": "LAD", "position": "DH",
         "stats": {"Hits": 1.4, "Total Bases": 2.8, "Home Runs": 0.40, "RBIs": 0.9, "Runs": 1.2, "Stolen Bases": 0.35}},
        {"name": "Mookie Betts", "team": "Los Angeles Dodgers", "team_abbr": "LAD", "position": "SS",
         "stats": {"Hits": 1.25, "Total Bases": 2.1, "Home Runs": 0.22, "RBIs": 0.8, "Runs": 1.0, "Stolen Bases": 0.15}},
        {"name": "Juan Soto", "team": "New York Mets", "team_abbr": "NYM", "position": "RF",
         "stats": {"Hits": 1.2, "Total Bases": 2.3, "Home Runs": 0.30, "RBIs": 0.9, "Runs": 1.1, "Stolen Bases": 0.1}},
        {"name": "Freddie Freeman", "team": "Los Angeles Dodgers", "team_abbr": "LAD", "position": "1B",
         "stats": {"Hits": 1.35, "Total Bases": 2.2, "Home Runs": 0.20, "RBIs": 0.85, "Runs": 0.9, "Stolen Bases": 0.08}},
        {"name": "Bobby Witt Jr.", "team": "Kansas City Royals", "team_abbr": "KC", "position": "SS",
         "stats": {"Hits": 1.45, "Total Bases": 2.5, "Home Runs": 0.25, "RBIs": 0.8, "Runs": 1.0, "Stolen Bases": 0.40}},
        {"name": "Gunnar Henderson", "team": "Baltimore Orioles", "team_abbr": "BAL", "position": "SS",
         "stats": {"Hits": 1.25, "Total Bases": 2.3, "Home Runs": 0.30, "RBIs": 0.8, "Runs": 1.1, "Stolen Bases": 0.20}},
        {"name": "Jose Ramirez", "team": "Cleveland Guardians", "team_abbr": "CLE", "position": "3B",
         "stats": {"Hits": 1.2, "Total Bases": 2.2, "Home Runs": 0.25, "RBIs": 0.9, "Runs": 0.9, "Stolen Bases": 0.30}},
        {"name": "Vladimir Guerrero Jr.", "team": "Toronto Blue Jays", "team_abbr": "TOR", "position": "1B",
         "stats": {"Hits": 1.4, "Total Bases": 2.3, "Home Runs": 0.22, "RBIs": 0.85, "Runs": 0.85, "Stolen Bases": 0.05}},
        {"name": "Corey Seager", "team": "Texas Rangers", "team_abbr": "TEX", "position": "SS",
         "stats": {"Hits": 1.3, "Total Bases": 2.4, "Home Runs": 0.32, "RBIs": 0.8, "Runs": 0.9, "Stolen Bases": 0.05}},
        {"name": "Yordan Alvarez", "team": "Houston Astros", "team_abbr": "HOU", "position": "DH",
         "stats": {"Hits": 1.3, "Total Bases": 2.5, "Home Runs": 0.34, "RBIs": 1.0, "Runs": 0.9, "Stolen Bases": 0.03}},
        {"name": "Marcus Semien", "team": "Texas Rangers", "team_abbr": "TEX", "position": "2B",
         "stats": {"Hits": 1.15, "Total Bases": 1.9, "Home Runs": 0.18, "RBIs": 0.7, "Runs": 0.95, "Stolen Bases": 0.12}},
    ],
    "basketball_wnba": [
        {"name": "A'ja Wilson", "team": "Las Vegas Aces", "team_abbr": "LV", "position": "F",
         "stats": {"Points": 26.9, "Rebounds": 11.9, "Assists": 2.3, "3-Pointers Made": 0.4, "Pts+Reb+Ast": 41.1}},
        {"name": "Caitlin Clark", "team": "Indiana Fever", "team_abbr": "IND", "position": "G",
         "stats": {"Points": 19.2, "Rebounds": 5.7, "Assists": 8.4, "3-Pointers Made": 3.1, "Pts+Reb+Ast": 33.3}},
        {"name": "Breanna Stewart", "team": "New York Liberty", "team_abbr": "NY", "position": "F",
         "stats": {"Points": 20.4, "Rebounds": 8.5, "Assists": 3.5, "3-Pointers Made": 1.3, "Pts+Reb+Ast": 32.4}},
        {"name": "Napheesa Collier", "team": "Minnesota Lynx", "team_abbr": "MIN", "position": "F",
         "stats": {"Points": 20.4, "Rebounds": 9.7, "Assists": 3.4, "3-Pointers Made": 1.0, "Pts+Reb+Ast": 33.5}},
        {"name": "Sabrina Ionescu", "team": "New York Liberty", "team_abbr": "NY", "position": "G",
         "stats": {"Points": 18.2, "Rebounds": 4.4, "Assists": 6.2, "3-Pointers Made": 2.8, "Pts+Reb+Ast": 28.8}},
        {"name": "Arike Ogunbowale", "team": "Dallas Wings", "team_abbr": "DAL", "position": "G",
         "stats": {"Points": 22.2, "Rebounds": 3.7, "Assists": 4.9, "3-Pointers Made": 2.6, "Pts+Reb+Ast": 30.8}},
        {"name": "Kelsey Plum", "team": "Los Angeles Sparks", "team_abbr": "LA", "position": "G",
         "stats": {"Points": 17.8, "Rebounds": 2.7, "Assists": 4.2, "3-Pointers Made": 2.3, "Pts+Reb+Ast": 24.7}},
        {"name": "Jewell Loyd", "team": "Las Vegas Aces", "team_abbr": "LV", "position": "G",
         "stats": {"Points": 19.7, "Rebounds": 3.7, "Assists": 3.4, "3-Pointers Made": 2.5, "Pts+Reb+Ast": 26.8}},
        {"name": "Alyssa Thomas", "team": "Phoenix Mercury", "team_abbr": "PHX", "position": "F",
         "stats": {"Points": 10.9, "Rebounds": 8.4, "Assists": 7.9, "3-Pointers Made": 0.1, "Pts+Reb+Ast": 27.2}},
        {"name": "Angel Reese", "team": "Chicago Sky", "team_abbr": "CHI", "position": "F",
         "stats": {"Points": 13.6, "Rebounds": 13.1, "Assists": 1.9, "3-Pointers Made": 0.1, "Pts+Reb+Ast": 28.6}},
        {"name": "Kahleah Copper", "team": "Phoenix Mercury", "team_abbr": "PHX", "position": "G",
         "stats": {"Points": 21.1, "Rebounds": 4.3, "Assists": 2.3, "3-Pointers Made": 2.0, "Pts+Reb+Ast": 27.7}},
    ],
    "americanfootball_nfl": [
        {"name": "Patrick Mahomes", "team": "Kansas City Chiefs", "team_abbr": "KC", "position": "QB",
         "stats": {"Passing Yards": 261.4, "Passing TDs": 1.6, "Rushing Yards": 18.0, "Receiving Yards": 0.0, "Receptions": 0.0}},
        {"name": "Josh Allen", "team": "Buffalo Bills", "team_abbr": "BUF", "position": "QB",
         "stats": {"Passing Yards": 245.8, "Passing TDs": 1.8, "Rushing Yards": 32.0, "Receiving Yards": 0.0, "Receptions": 0.0}},
        {"name": "Lamar Jackson", "team": "Baltimore Ravens", "team_abbr": "BAL", "position": "QB",
         "stats": {"Passing Yards": 251.0, "Passing TDs": 2.1, "Rushing Yards": 55.0, "Receiving Yards": 0.0, "Receptions": 0.0}},
        {"name": "Christian McCaffrey", "team": "San Francisco 49ers", "team_abbr": "SF", "position": "RB",
         "stats": {"Rushing Yards": 92.0, "Receptions": 4.2, "Receiving Yards": 38.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Saquon Barkley", "team": "Philadelphia Eagles", "team_abbr": "PHI", "position": "RB",
         "stats": {"Rushing Yards": 113.0, "Receptions": 2.1, "Receiving Yards": 16.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Tyreek Hill", "team": "Miami Dolphins", "team_abbr": "MIA", "position": "WR",
         "stats": {"Receiving Yards": 81.0, "Receptions": 6.0, "Rushing Yards": 3.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Ja'Marr Chase", "team": "Cincinnati Bengals", "team_abbr": "CIN", "position": "WR",
         "stats": {"Receiving Yards": 96.0, "Receptions": 7.0, "Rushing Yards": 2.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "CeeDee Lamb", "team": "Dallas Cowboys", "team_abbr": "DAL", "position": "WR",
         "stats": {"Receiving Yards": 88.0, "Receptions": 6.5, "Rushing Yards": 4.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Justin Jefferson", "team": "Minnesota Vikings", "team_abbr": "MIN", "position": "WR",
         "stats": {"Receiving Yards": 92.0, "Receptions": 6.2, "Rushing Yards": 1.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Travis Kelce", "team": "Kansas City Chiefs", "team_abbr": "KC", "position": "TE",
         "stats": {"Receiving Yards": 64.0, "Receptions": 6.5, "Rushing Yards": 0.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Amon-Ra St. Brown", "team": "Detroit Lions", "team_abbr": "DET", "position": "WR",
         "stats": {"Receiving Yards": 85.0, "Receptions": 7.5, "Rushing Yards": 2.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
    ],
    "americanfootball_ncaaf": [
        {"name": "Carson Beck", "team": "Miami Hurricanes", "team_abbr": "MIA", "position": "QB",
         "stats": {"Passing Yards": 285.0, "Passing TDs": 2.2, "Rushing Yards": 8.0, "Receiving Yards": 0.0}},
        {"name": "Garrett Nussmeier", "team": "LSU Tigers", "team_abbr": "LSU", "position": "QB",
         "stats": {"Passing Yards": 298.0, "Passing TDs": 2.4, "Rushing Yards": 6.0, "Receiving Yards": 0.0}},
        {"name": "Drew Allar", "team": "Penn State Nittany Lions", "team_abbr": "PSU", "position": "QB",
         "stats": {"Passing Yards": 232.0, "Passing TDs": 1.8, "Rushing Yards": 14.0, "Receiving Yards": 0.0}},
        {"name": "Jeremiah Smith", "team": "Ohio State Buckeyes", "team_abbr": "OSU", "position": "WR",
         "stats": {"Receiving Yards": 84.0, "Passing Yards": 0.0, "Passing TDs": 0.0, "Rushing Yards": 3.0}},
        {"name": "Ryan Williams", "team": "Alabama Crimson Tide", "team_abbr": "ALA", "position": "WR",
         "stats": {"Receiving Yards": 78.0, "Passing Yards": 0.0, "Passing TDs": 0.0, "Rushing Yards": 2.0}},
        {"name": "Ollie Gordon II", "team": "Oklahoma State Cowboys", "team_abbr": "OKST", "position": "RB",
         "stats": {"Rushing Yards": 96.0, "Receiving Yards": 22.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Quinshon Judkins", "team": "Ohio State Buckeyes", "team_abbr": "OSU", "position": "RB",
         "stats": {"Rushing Yards": 88.0, "Receiving Yards": 14.0, "Passing Yards": 0.0, "Passing TDs": 0.0}},
        {"name": "Cade Klubnik", "team": "Clemson Tigers", "team_abbr": "CLEM", "position": "QB",
         "stats": {"Passing Yards": 268.0, "Passing TDs": 2.3, "Rushing Yards": 22.0, "Receiving Yards": 0.0}},
    ],
    "basketball_ncaab": [
        {"name": "Cooper Flagg", "team": "Duke Blue Devils", "team_abbr": "DUKE", "position": "F",
         "stats": {"Points": 19.4, "Rebounds": 7.5, "Assists": 4.2, "3-Pointers Made": 1.4}},
        {"name": "RJ Davis", "team": "North Carolina Tar Heels", "team_abbr": "UNC", "position": "G",
         "stats": {"Points": 17.6, "Rebounds": 3.2, "Assists": 3.5, "3-Pointers Made": 2.6}},
        {"name": "Mark Sears", "team": "Alabama Crimson Tide", "team_abbr": "ALA", "position": "G",
         "stats": {"Points": 18.6, "Rebounds": 4.2, "Assists": 5.1, "3-Pointers Made": 3.0}},
        {"name": "Johni Broome", "team": "Auburn Tigers", "team_abbr": "AUB", "position": "F",
         "stats": {"Points": 18.0, "Rebounds": 10.8, "Assists": 2.9, "3-Pointers Made": 0.8}},
        {"name": "Hunter Dickinson", "team": "Kansas Jayhawks", "team_abbr": "KU", "position": "C",
         "stats": {"Points": 17.3, "Rebounds": 10.2, "Assists": 2.6, "3-Pointers Made": 0.6}},
        {"name": "Braden Smith", "team": "Purdue Boilermakers", "team_abbr": "PUR", "position": "G",
         "stats": {"Points": 16.2, "Rebounds": 4.4, "Assists": 8.7, "3-Pointers Made": 2.1}},
        {"name": "Kon Knueppel", "team": "Duke Blue Devils", "team_abbr": "DUKE", "position": "G",
         "stats": {"Points": 14.4, "Rebounds": 4.0, "Assists": 2.7, "3-Pointers Made": 2.2}},
        {"name": "Walter Clayton Jr.", "team": "Florida Gators", "team_abbr": "FLA", "position": "G",
         "stats": {"Points": 18.3, "Rebounds": 3.6, "Assists": 4.2, "3-Pointers Made": 2.7}},
    ],
}

# Realistic injury pools per sport (player, team_abbr, position, status, injury).
INJURIES = {
    "baseball_mlb": [
        ("Gerrit Cole", "NYY", "SP", "IL-60", "Elbow (Tommy John)"),
        ("Ronald Acuna Jr.", "ATL", "RF", "IL-10", "Knee (ACL)"),
        ("Mike Trout", "LAA", "CF", "IL-10", "Knee (meniscus)"),
        ("Spencer Strider", "ATL", "SP", "IL-60", "Elbow (internal brace)"),
        ("Fernando Tatis Jr.", "SD", "RF", "Day-To-Day", "Quad tightness"),
        ("Corbin Carroll", "ARI", "CF", "Day-To-Day", "Lower back"),
        ("Adley Rutschman", "BAL", "C", "Day-To-Day", "Oblique"),
        ("Jacob deGrom", "TEX", "SP", "IL-15", "Forearm"),
        ("Bryce Harper", "PHI", "1B", "Day-To-Day", "Wrist soreness"),
        ("Wander Franco", "TB", "SS", "Restricted", "Administrative leave"),
        ("Sandy Alcantara", "MIA", "SP", "IL-15", "Shoulder fatigue"),
        ("Julio Rodriguez", "SEA", "CF", "Day-To-Day", "Ankle"),
        ("Matt Olson", "ATL", "1B", "Day-To-Day", "Hand contusion"),
        ("Tyler Glasnow", "LAD", "SP", "IL-15", "Elbow tendinitis"),
        ("Yordan Alvarez", "HOU", "DH", "Day-To-Day", "Hand soreness"),
        ("Framber Valdez", "HOU", "SP", "Probable", "Blister"),
    ],
    "basketball_wnba": [
        ("Caitlin Clark", "IND", "G", "Questionable", "Quad strain"),
        ("Cameron Brink", "LA", "F", "Out", "Knee (ACL)"),
        ("Diana Taurasi", "PHX", "G", "Day-To-Day", "Ankle"),
        ("Chelsea Gray", "LV", "G", "Questionable", "Foot"),
        ("Satou Sabally", "PHX", "F", "Out", "Shoulder"),
        ("Aliyah Boston", "IND", "F", "Probable", "Ankle"),
        ("Jonquel Jones", "NY", "F", "Questionable", "Ankle sprain"),
        ("Brittney Griner", "ATL", "C", "Day-To-Day", "Calf"),
        ("Kelsey Mitchell", "IND", "G", "Probable", "Hip"),
        ("Nneka Ogwumike", "SEA", "F", "Day-To-Day", "Lower back"),
        ("Marina Mabrey", "CONN", "G", "Questionable", "Knee soreness"),
        ("Rhyne Howard", "ATL", "G", "Out", "Hand fracture"),
        ("Dearica Hamby", "LA", "F", "Probable", "Ankle"),
        ("Skylar Diggins", "SEA", "G", "Day-To-Day", "Hamstring"),
        ("Kahleah Copper", "PHX", "G", "Questionable", "Knee management"),
    ],
    "americanfootball_nfl": [
        ("Christian McCaffrey", "SF", "RB", "Questionable", "Achilles"),
        ("Aaron Rodgers", "NYJ", "QB", "Out", "Hamstring"),
        ("Justin Jefferson", "MIN", "WR", "Questionable", "Hamstring"),
        ("Nick Bosa", "SF", "DE", "Day-To-Day", "Hip"),
        ("Cooper Kupp", "LAR", "WR", "Doubtful", "Ankle"),
        ("Saquon Barkley", "PHI", "RB", "Probable", "Groin"),
        ("Joe Burrow", "CIN", "QB", "Out", "Wrist"),
        ("Davante Adams", "LV", "WR", "Questionable", "Hamstring"),
        ("Trent Williams", "SF", "OT", "Out", "Ankle"),
        ("Lamar Jackson", "BAL", "QB", "Probable", "Knee"),
        ("Travis Kelce", "KC", "TE", "Questionable", "Knee"),
        ("Micah Parsons", "DAL", "LB", "Day-To-Day", "Ankle"),
        ("Tua Tagovailoa", "MIA", "QB", "Doubtful", "Concussion protocol"),
        ("Breece Hall", "NYJ", "RB", "Questionable", "Knee"),
        ("CeeDee Lamb", "DAL", "WR", "Probable", "Shoulder"),
    ],
    "americanfootball_ncaaf": [
        ("Carson Beck", "MIA", "QB", "Questionable", "Elbow"),
        ("Will Howard", "OSU", "QB", "Probable", "Hand"),
        ("Ollie Gordon II", "OKST", "RB", "Day-To-Day", "Ankle"),
        ("Ryan Williams", "ALA", "WR", "Questionable", "Hamstring"),
        ("Jeremiah Smith", "OSU", "WR", "Probable", "Shoulder"),
        ("Drew Allar", "PSU", "QB", "Day-To-Day", "Ankle"),
        ("Cade Klubnik", "CLEM", "QB", "Probable", "Knee"),
        ("Quinshon Judkins", "OSU", "RB", "Questionable", "Hip"),
        ("Garrett Nussmeier", "LSU", "QB", "Probable", "Throwing hand"),
        ("Luther Burden III", "MIZ", "WR", "Out", "Ankle"),
        ("Kaleb Johnson", "IOWA", "RB", "Day-To-Day", "Shoulder"),
        ("Dillon Gabriel", "ORE", "QB", "Probable", "Ribs"),
        ("Tetairoa McMillan", "ARIZ", "WR", "Questionable", "Knee"),
        ("Omarion Hampton", "UNC", "RB", "Day-To-Day", "Ankle"),
        ("Nico Iamaleava", "TENN", "QB", "Probable", "Concussion protocol"),
    ],
    "basketball_ncaab": [
        ("RJ Davis", "UNC", "G", "Questionable", "Ankle"),
        ("Hunter Dickinson", "KU", "C", "Day-To-Day", "Shoulder"),
        ("Mark Sears", "ALA", "G", "Probable", "Hip"),
        ("Cooper Flagg", "DUKE", "F", "Probable", "Ankle"),
        ("Johni Broome", "AUB", "F", "Day-To-Day", "Back"),
        ("Braden Smith", "PUR", "G", "Probable", "Wrist"),
        ("Walter Clayton Jr.", "FLA", "G", "Questionable", "Calf"),
        ("Kon Knueppel", "DUKE", "G", "Probable", "Hand"),
        ("Zvonimir Ivisic", "ARK", "C", "Day-To-Day", "Knee"),
        ("Boogie Fland", "ARK", "G", "Out", "Thumb (surgery)"),
        ("Tahaad Pettiford", "AUB", "G", "Probable", "Ankle"),
        ("PJ Haggerty", "MEM", "G", "Questionable", "Hamstring"),
        ("Otega Oweh", "UK", "G", "Day-To-Day", "Foot"),
        ("Vladislav Goldin", "MICH", "C", "Probable", "Knee"),
        ("JT Toppin", "TTU", "F", "Day-To-Day", "Shoulder"),
    ],
}
